Update footer.html
fossasia/2012.fossasia.org pull request #116
Opened 2017-12-27 19:11 UTC by arjunpandey2003

Fixes issue#109
Updated head.html

2017-12-27 19:35 UTC, arjunpandey2003 commented
https://arjunpandey2003.github.io/2012.fossasiarjunp.org/

2017-12-27 19:35 UTC, arjunpandey2003 commented
why is my vk logo coming out like that

2017-12-27 19:39 UTC, 0x48piraj requested changes
Squash! :+1:

2017-12-27 19:41 UTC, arjunpandey2003 commented
@0x48piraj can u tell me why my vk logo is coming out like that

2017-12-27 20:09 UTC, 0x48piraj commented
![image](https://user-images.githubusercontent.com/5800726/34392073-f967b82e-eb6f-11e7-8baa-14363dc437cb.png)

2017-12-28 00:31 UTC, isuruAb reviewed
some icons are missing. please check

2017-12-28 14:41 UTC, anshumanv reviewed
Test link not working.

2017-12-28 15:07 UTC, arjunpandey2003 commented
@anshumanv ttps://arjunpandey2003.github.io/2012.fossasiarjunpcde.org/.

2017-12-28 15:15 UTC, anshumanv commented on _includes/footer.html
> +                                <li><a target="_self" href="https://github.com/fossasia"><i class="fa fa-github fa-lg"></i></a></li>
remove `fa-lg` from the class

2017-12-28 15:15 UTC, anshumanv commented on _includes/footer.html
> +                                <li><a target="_self" href="https://github.com/fossasia"><i class="fa fa-github fa-lg"></i></a></li>
See other's comments too.

2017-12-29 05:42 UTC, closed without merging