Added Social Icons
fossasia/2012.fossasia.org pull request #120
Opened 2017-12-28 09:19 UTC by saarthakchats

2017-12-28 13:59 UTC, duttaditya18 commented
Preview Link?

2017-12-28 14:12 UTC, saarthakchats commented
https://saarthakchats.github.io/2012.fossasia.org

2017-12-28 14:13 UTC, saarthakchats commented
@duttaditya18

2017-12-28 14:14 UTC, duttaditya18 commented
@saarthakchats Cannot see any changes.

2017-12-28 14:18 UTC, akshatnitd approved these changes
LGTM !
Please fill the PR template properly from next time.

2017-12-28 14:19 UTC, saarthakchats commented
@akshatnitd Filled it. Thanks for letting me know. Will definitely make sure from the next time.

2017-12-28 14:19 UTC, isuruAb reviewed
where is the sponsor section ?

2017-12-28 14:22 UTC, saarthakchats commented
It's the partners' section. Right below the landing

2017-12-28 14:22 UTC, saarthakchats commented
@isuruAb

2017-12-28 18:12 UTC, isuruAb approved these changes

2017-12-28 20:42 UTC, anshumanv commented on _includes/header.html
> +            	<a href="workshops.html">Event Elements</a>
Clicking on Event Elements shouldn't take us to `/workshops.html` ideally.

2017-12-29 17:39 UTC, saarthakchats commented
@anshumanv Turned it to hashtag, if some relevant page is added, I will add that link later

2017-12-30 01:46 UTC, nzec approved these changes
Cool!

2017-12-30 08:24 UTC, vaibhavsingh97 requested changes
@saarthakchats Please change PR title to `Fixes #<issue-number>: <commit-message>` and also change your commit message tto something meaningful

2017-12-30 08:30 UTC, arjunpandey2003 commented
@saarthakchats there is a problem, you have added designer tab to the event element dropdown but still there is a design tab right next to it. Please take a look
<img width="1182" alt="screen shot 2017-12-30 at 1 59 55 pm" src="https://user-images.githubusercontent.com/25302509/34452643-c1e65e5e-ed69-11e7-970d-bf5ffc9b029b.png">

2017-12-30 08:31 UTC, arjunpandey2003 commented
oh sorry my bad they are two different pages
i got confused

2017-12-30 08:57 UTC, anshumanv approved these changes

2017-12-30 10:06 UTC, saurabhjn76 approved these changes

2017-12-30 11:05 UTC, saarthakchats commented
@vaibhavsingh97 @anshumanv @saurabhjn76 Pls merge

2017-12-30 11:08 UTC, vaibhavsingh97 commented
@saarthakchats Please use squash commits and use something meaningful commit message

2017-12-30 11:13 UTC, saarthakchats commented
Have squashed, pls merge. @vaibhavsingh97

2017-12-30 11:20 UTC, ParthS007 approved these changes

2017-12-30 11:21 UTC, merged