Fixed #121: Added and removed icons
fossasia/2012.fossasia.org pull request #122
Opened 2017-12-28 10:46 UTC by samyakbvs

Added the Dribbble link and icon + Removed the bugged GitHub links in the footer as well as the Header

Test link - https://samyakbvs.github.io/samyakjain-jainsamyak-2012.fossasia.org/

Closes #121

2017-12-28 18:27 UTC, vaibhavsingh97 commented on _includes/footer.html
> +                                <li><a target="_self" href="https://www.fossasia.net"><i class="icon social_dribbble"></i></a></li>
this is not a dribble link

2017-12-28 18:27 UTC, vaibhavsingh97 commented on _includes/footer.html
> +                                <li><a target="_self" href="https://www.fossasia.net"><i class="icon social_dribbble"></i></a></li>
This is not a dribble link

2017-12-28 18:31 UTC, samyakbvs commented
But its used on Gci17.fossasia.org as well?

2017-12-28 18:32 UTC, samyakbvs commented
@vaibhavsingh97 so should I remove it from there too?

2017-12-29 07:45 UTC, vaibhavsingh97 requested changes

2017-12-29 07:45 UTC, vaibhavsingh97 commented on _includes/footer.html
> +                                <li><a href="https://in.pinterest.com/pin/390476230184177529/"><i class=" ti-pinterest" aria-hidden="true"></i></a></li>
Remove it as I can find any pinterst link of FOSSASIA. It's a post link

2017-12-29 07:46 UTC, vaibhavsingh97 commented
> But its used on Gci17.fossasia.org as well?

Please remove from there. Feel free to raise issue and fix it

2017-12-29 12:54 UTC, samyakbvs commented
Revised test link - https://samyakbvs.github.io/dumdaayadaadum-jainsamyak-2012.fossasia.org/

2017-12-31 09:41 UTC, arjunpandey2003 commented
@samyakbvs you have two target attrs in the google plus icon
<img width="790" alt="screen shot 2017-12-31 at 3 11 30 pm" src="https://user-images.githubusercontent.com/25302509/34460718-eda568fe-ee3c-11e7-9bc7-1a887d2d7590.png">

2017-12-31 09:47 UTC, samyakbvs commented
@arjunpandey2003 I think its supposed to be like that, bcs I didn't add it

2017-12-31 09:48 UTC, arjunpandey2003 commented
@samyakbvs ohk

2018-01-01 13:24 UTC, harshit98 commented
@samyakbvs There should be only 1 target value. Remove the _self value of target.

2018-01-01 14:43 UTC, harshit98 approved these changes

2018-01-01 14:43 UTC, merged