Update header.html
fossasia/2012.fossasia.org pull request #123
Opened 2017-12-29 15:38 UTC by arjunpandey2003

Fixes #117 
Updated header.html

2017-12-29 17:35 UTC, saarthakchats commented
Deploy link?

2017-12-29 18:11 UTC, arjunpandey2003 commented
https://arjunpandey2003.github.io/2012.fossasiaunicodef.org/.

2017-12-30 08:33 UTC, vaibhavsingh97 commented
@arjunpandey2003 Please squash your commit and use some meaningful commit message. Please change your PR title to Fixes #<issue-number: <commit-message>. Please follow best practices

2017-12-30 08:34 UTC, vaibhavsingh97 requested changes

2017-12-30 08:34 UTC, vaibhavsingh97 commented on _includes/header.html
> +                <li><a target="_self" href="http://gci17.fossasia.org">GCI Official Site</a></li>
These are not FOSSASIA Events

2017-12-30 08:34 UTC, vaibhavsingh97 commented on _includes/header.html
> +                <li><a target="_self" href="https://summerofcode.withgoogle.com/archive/2017/organizations/5936828200779776/">GSoC Fossasia</a></li>
same

2017-12-30 08:34 UTC, vaibhavsingh97 commented on _includes/header.html
> +                <li><a target="_self" href="http://gci17.fossasia.org">GCI Official Site</a></li>
This can come under `Quick links`

2017-12-30 09:39 UTC, closed without merging