Fixes #133 :Improved indentation and removed blank spaces to improve Code Quality
fossasia/2012.fossasia.org pull request #134
Opened 2018-01-02 17:13 UTC by saarthakchats

Fixes #133

2018-01-02 17:24 UTC, akshatnitd commented on _includes/footer.html
> +        </div>
One `</div>` missing

2018-01-02 17:27 UTC, vaibhavsingh97 requested changes
LGTM!

2018-01-02 17:27 UTC, vaibhavsingh97 commented on _includes/footer.html
> +                            <p> FOSSASIA develops Open Source software and hardware for conversational AIs, science and event management with a global developer community from its base in Asia. The o
`<p>` and `<span>` should be in the same line

2018-01-02 17:27 UTC, vaibhavsingh97 commented on _includes/footer.html
> +
Remove one blank line from here

2018-01-02 17:28 UTC, vaibhavsingh97 commented on _includes/footer.html
> +        </div>
nice catch 😅 Thanks

2018-01-02 17:36 UTC, saarthakchats commented
@vaibhavsingh97

2018-01-02 18:34 UTC, vaibhavsingh97 commented
@saarthakchats add div before `footer`

2018-01-02 19:26 UTC, saarthakchats commented
@vaibhavsingh97

2018-01-03 05:57 UTC, saarthakchats commented
@harshit98

2018-01-03 06:36 UTC, duttaditya18 commented on _includes/footer.html
> +        </div>
Fix the indentation here.

2018-01-03 06:39 UTC, saarthakchats commented
@duttaditya18

2018-01-03 06:41 UTC, nzec approved these changes
Cool!

2018-01-03 07:14 UTC, arjunpandey2003 commented
Actually here you have left some whitespace
<img width="144" alt="screen shot 2018-01-03 at 12 41 41 pm" src="https://user-images.githubusercontent.com/25302509/34511727-947cc670-f083-11e7-8a4f-c668c500fd96.png">
The <span> and <p> should be inline with the <ul> tag not the <li>

2018-01-03 07:27 UTC, saarthakchats commented
@arjunpandey2003 
Please specify where?

2018-01-03 07:28 UTC, arjunpandey2003 commented
17-18 line

2018-01-03 07:45 UTC, saarthakchats commented
I DON'T SEE A PROBLEM

2018-01-03 07:49 UTC, arjunpandey2003 commented
@saarthakchats in the 18-19 line you have indented more as in left more space, causing it to be in-line with the li in the 23-27 line, instead the tags should come in-line with the ul on line 22

2018-01-03 07:52 UTC, arjunpandey2003 commented
@saarthakchats Perfect

2018-01-03 07:52 UTC, saarthakchats commented
@arjunpandey2003 I believe its fine now

2018-01-03 07:53 UTC, arjunpandey2003 commented
@saarthakchats sorry i spotted one more problem, line 45, Check it out

2018-01-03 13:29 UTC, harshit98 approved these changes
LGTM 💯

2018-01-03 13:29 UTC, merged

2018-01-03 14:26 UTC, saarthakchats commented
@harshit98 Can my task be approved?