Update index.html
fossasia/2012.fossasia.org pull request #175
Opened 2018-10-24 07:20 UTC by Jeewal

2018-10-24 11:30 UTC, Masquerade0097 commented
@Jeewal Please fill in the PR description.

2018-10-24 12:23 UTC, akshatnitd requested changes

2018-10-24 12:23 UTC, akshatnitd commented on index.html
> +Skip to content
These changes are extra and you need to remove it from the Pull Request.

2018-10-24 12:23 UTC, akshatnitd commented on index.html
> +© 2018 GitHub, Inc.
These changes are extra and you need to remove it from the Pull Request.

2018-10-24 12:42 UTC, Jeewal commented
@akshatnitd  Please have a look

2018-10-24 12:52 UTC, abishekvashok requested changes
Please fix Travis :)

2018-10-24 14:38 UTC, Jeewal commented
https://github.com/fossasia/2012.fossasia.org/pull/176
I hope this can help fix my travis error.

2018-10-24 14:41 UTC, Jeewal commented
@abishekvashok @akshatnitd

2018-10-24 15:00 UTC, abishekvashok commented
Can I know which issue does this solve?

2018-10-24 15:02 UTC, Jeewal commented
The failing of Travis due to the Ruby version being 2.2.0. Whereas, Ruby version 2.3.0 is required

2018-10-24 15:32 UTC, abishekvashok commented
The issue in the tracker pls? Travis is fixed

2018-10-25 02:59 UTC, Jeewal commented
https://github.com/fossasia/2012.fossasia.org/issues/165

2018-10-25 02:59 UTC, Jeewal commented
Has been solved

2018-10-25 04:14 UTC, Masquerade0097 approved these changes
LGTM

2018-10-25 20:23 UTC, YashKumarVerma requested changes
1. commits not squashed 
2. vague (too borad) PR Name

2018-10-26 07:21 UTC, closed without merging

2018-10-28 05:10 UTC, prateekiiest commented
@Jeewal do you want to open a new PR with the changes