Updated Schedule in index.html
fossasia/2012.fossasia.org pull request #179
Opened 2018-10-26 09:06 UTC by Jeewal

Updated Schedule as In the Linked PDF in index.html of Issue https://github.com/fossasia/2012.fossasia.org/issues/165

2018-10-26 09:10 UTC, Jeewal commented
@YashKumarVerma

2018-10-26 10:18 UTC, YashKumarVerma requested changes
Preview Link missing

2018-10-26 15:23 UTC, Jeewal commented
https://jeewal.github.io/2012.fossasia.org/ @YashKumarVerma

2018-10-26 20:57 UTC, YashKumarVerma approved these changes

2018-10-27 03:56 UTC, simsausaurabh commented on index.html
> +                                    <p> 7:00AM- 7:00PMExcursion and gathering material "Between Folk Art and Industrial production" in Mekong and arrival in Cantho </p>
Keep space between time and text.

2018-10-27 03:57 UTC, simsausaurabh commented on index.html
> +
Keep space between time and text.

2018-10-27 03:57 UTC, simsausaurabh commented on index.html
> +                                    <p>9:00AM-12:00PM and1:30PM-5:00PM Libre Graphics and Open Source Design Workshops and Sessions
Please follow up in whole file and fix it at all places.

2018-10-27 06:05 UTC, closed without merging