Indented Codebase and added informing comments
fossasia/2012.fossasia.org pull request #188
Opened 2018-11-15 00:29 UTC by saarthakchats

2018-11-15 03:19 UTC, liveHarshit approved these changes

2018-11-16 16:28 UTC, utkarsh2102 requested changes
Going to the last, I don't think the indentation is fixed there.
The closing tags are far apart from where they should be.
Also, cannot it be reduced to 4 spaces?

2018-11-18 06:45 UTC, jogendra approved these changes

2018-11-18 06:45 UTC, merged

2018-11-26 12:54 UTC, niteshkumarniranjan commented
@utkarsh2102 Fixed it here https://github.com/fossasia/2012.fossasia.org/pull/193