Optimize JS Files
fossasia/2012.fossasia.org pull request #202
Opened 2018-12-07 04:44 UTC by Ryan10145

Optimizes the JS files by:
- Removing unused files
- Minimizing all .min.js files

Fixes #201 

Preview Link: https://ryan10145.github.io/2012.fossasia.org/

2018-12-08 05:07 UTC, jogendra requested changes

2018-12-08 05:07 UTC, jogendra commented on 500.html
> -					<script src="js/twitterfetcher.min.js"></script>
Why did you deleted this?

2018-12-08 12:29 UTC, rcya1 commented on 500.html
> -					<script src="js/twitterfetcher.min.js"></script>
@jogendra It was because those pages (404 and 500) don’t contain any twitter feeds and shouldn’t, so I removed the js file as it was unnecessary. I can add it back in if it is better for uniformity though.

2018-12-08 18:32 UTC, Ryan10145 commented
@jogendra I've added those lines back in to maintain uniformity between the HTML files, please check again.

2018-12-09 05:05 UTC, batbrain7 commented
@Akshat-Jain please review

2018-12-09 08:32 UTC, abishekvashok requested changes
The ajax jQuery versions are optimized by default.

2018-12-09 14:59 UTC, Ryan10145 commented
@abishekvashok Ok, I've reverted the changes so it now uses the ajax version.

2018-12-11 23:17 UTC, AakashMallik commented
@Ryan10145 So you have deleted all the unused files, right? I mean, it is just that.

2018-12-11 23:45 UTC, Ryan10145 commented
@AakashMallik I’ve also minimized the JS files to reduce file size and slightly improve performance. Other than that, yes, the PR deletes many unused files that are cluttering the repo.

2019-04-01 03:32 UTC, closed without merging