Links&Displaying on phones
fossasia/2012.fossasia.org pull request #65
Opened 2017-12-13 22:32 UTC by Shizerq

Fixed links in design and exhibition. Main page looks now good on phones and iPads. Fix of #62 and #63

2017-12-13 23:09 UTC, harshit98 commented on CNAME
> +>>>>>>> gh-pages
Update your branch. Looks like you have not updated your branch.

2017-12-13 23:09 UTC, harshit98 commented on stylesheets/sidebar.css
> +>>>>>>> gh-pages
Same here. Remove `<<<HEAD` and `>>>gh-pages`.

2017-12-15 14:54 UTC, akshatnitd requested changes
Correct the indentation and check inline comments

2017-12-15 14:54 UTC, akshatnitd commented on CNAME
> +<<<<<<< HEAD
Remove ```HEAD``` and ```gh-pages```

2017-12-15 14:54 UTC, akshatnitd commented on stylesheets/sidebar.css
> +<<<<<<< HEAD
Remove ```HEAD``` and ```gh-pages```

2017-12-15 14:54 UTC, akshatnitd commented on stylesheets/sidebar.css
> +					display: block;
Correct the identation

2017-12-15 14:54 UTC, akshatnitd commented on stylesheets/sidebar.css
> +					display: block;
Check Indentation

2017-12-15 14:54 UTC, akshatnitd commented on stylesheets/sidebar.css
> +					display: block;
Check indentation

2017-12-15 19:13 UTC, anshumanv requested changes
Please fix all indentations.

2017-12-15 19:13 UTC, anshumanv commented on stylesheets/sidebar.css
> +        display: block;
Indentation

2017-12-15 19:13 UTC, anshumanv commented on stylesheets/sidebar.css
> +       float: right;
Indent

2017-12-15 19:13 UTC, anshumanv commented on stylesheets/sidebar.css
> +}
Indent

2017-12-17 15:03 UTC, mariobehling commented
This is not bringing the project forward directly. What we really need is a proper top menu bar as at fossasia.org.

2017-12-22 22:12 UTC, mariobehling commented
Closing this due to inactivity. Please make a new PR, if this issue persists.

2017-12-22 22:12 UTC, closed without merging