Removed "?" GitHub link. Replaced it.
fossasia/2012.fossasia.org pull request #88
Opened 2017-12-21 23:24 UTC by saarthakchats

2017-12-22 12:30 UTC, 0x48piraj requested changes
Provide a test link @saarthakchats 
Also, squash the commits! :+1:

2017-12-22 12:32 UTC, STEdirisuriya commented
Please add more details about what you did

2017-12-22 12:33 UTC, abishekvashok requested changes
Also pls squash your commits. If you can't find a good squashing tutorial, query up in the gitter channel.

2017-12-22 12:33 UTC, abishekvashok commented on _includes/footer.html
> +                                <li><a target="_self" href="https://github.com/fossasia"><i class="icon social_linkedin icon-large"></i></a></li>
We don't need icon-large do we

2017-12-22 13:47 UTC, nzec requested changes
Rather than removing it, you could have just put a Github image or linked FontAwesome.

2017-12-22 22:12 UTC, mariobehling commented
Please provide add a Github icon.

2017-12-23 19:56 UTC, ParthS007 requested changes
@saarthakchats  Please do the suggested changes 👍

2017-12-24 12:40 UTC, ParthS007 commented
@saarthakchats  PLease provide a Preview link also 👍

2017-12-24 13:40 UTC, closed without merging